spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 50           # 최대 커넥션 수
            minimum-idle: 31 # 최대 커넥션 수
    batch:
        jdbc:
            platform: mysql
            initialize-schema: always
        job:
            name: ${job.name:NONE} # --job.name=helloWorldJob
            enabled: true
    jpa:
#        properties:
#            hibernate:
#                format_sql: true
#        generate-ddl: true
#        show-sql: true
        hibernate:
            ddl-auto: none
#            ddl-auto: update

logging:
    level:
        root: info
#        org.hibernate.orm.jdbc.bind: trace
#        org.hibernate.type.descriptor.sql.BasicBinder: trace
