spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    batch:
        jdbc:
            platform: mysql

        job:
            name: ${job.name:NONE} # --job.name=
            enabled: true

logging:
    level:
        org.springframework.batch: INFO